POST http://localhost:3001/api/productos/producto HTTP/1.1
Content-Type: application/json

{
    "name": "Pizza Queso, Jamón y Champiñones",
  "price": 69.9,
  "photo": "pizzas_11",
  "categoria": "Pizzas"
}
###
GET  http://localhost:3001/api/productos/producto HTTP/1.1
Content-Type: application/json


###
DELETE http://localhost:3001/api/productos/eliminar-producto/640644ca2df39bca2701a5f2 HTTP/1.1
Content-Type: application/json



###
GET  http://localhost:3001/api/productos/producto/donas HTTP/1.1
Content-Type: application/json


###
GET http://localhost:3001/api/productos/get-producto/6400e922ed6a9fe40f0c2e38 HTTP/1.1
Content-Type: application/json




###
GET http://localhost:3001/ HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/api/ordenes/orden HTTP/1.1
Content-Type: application/json

{
    "nombre": "Pedro",
  "fecha": "03-02-2000",
  "total": 342,
  "pedido": [
    {
      "_id": "640786ec32bd6be7e80042d8",
      "name": "Café Caramel con Chocolate",
      "price": 59.9
  },
  {
      "_id": "640786ec32bd6be7e80042d8",
      "name": "Café con Chocolate",
      "price": 59.9
  },
  {
      "_id": "640786ec32bd6be7e80042d8",
      "name": "Café Caramel",
      "price": 59.9
  }
  
  ]
    
}

###
GET  http://localhost:3001/api/ordenes/orden HTTP/1.1
Content-Type: application/json
